server:
  port: 9090

spring:
  application:
    name: consumer-service
  activemq:
    broker-url: tcp://192.168.0.111:61616
    user: amdin
    password: admin
    pool:
      enabled: false
    packages:
      trust-all: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:123456@localhost:10001/eureka/




