server:
  port: 9999
spring:
  application:
    name: service-zuul

#指定服务中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:123456@localhost:10001/eureka/

#feign.hystrix.enabled=true


zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: consumer-service
    api-b:
      path: /api-b/**
      serviceId: service-feign
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
