server:
  port: 7070

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          username: liquanyu
          password: quan527317488
          uri: https://github.com/liquanyu/spring-config

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:123456@localhost:10001/eureka/